#!/usr/bin/env python3
"""Generate runtime adapters from .agents; --check is read-only and fails on drift."""
from __future__ import annotations

import argparse
import json
import re
import tomllib
from pathlib import Path

from check_agent_organization import load_core, load_json, roster, organization_fields

MARKER = 'Generated by scripts/generate_agent_adapters.py'
MANIFEST = '.agents/generated-files.json'
COMMON = ('Read `AGENTS.md` and `.agents/ORGANIZATION.md` before coordinating work.\n'
          'Use the assigned role only; preserve its evidence and safety requirements.\n'
          'Edit canonical roles and adapter settings, then regenerate; do not hand-edit adapters.\n\n')


def quote(value: str) -> str:
    # JSON basic strings are a compatible subset for these TOML/YAML strings.
    return json.dumps(value, ensure_ascii=False)


def load_settings(root: Path, vendor: str, names: set[str]) -> dict:
    data = load_json(root / f'.agents/adapters/{vendor}.json')
    allowed = {'schema_version', 'format', 'roles'} | ({'default_model'} if vendor == 'opencode' else {'max_concurrent_threads_per_session'})
    if data.keys() - allowed or data.get('schema_version') != 1:
        raise ValueError(f'{vendor}: unsupported settings/schema')
    expected = 'opencode-v1' if vendor == 'opencode' else 'standalone-toml'
    if data.get('format') != expected:
        raise ValueError(f'{vendor}: unsupported adapter format')
    overrides = data.get('roles', {})
    if not isinstance(overrides, dict) or overrides.keys() - names:
        raise ValueError(f'{vendor}: unknown role overrides')
    for name, values in overrides.items():
        keys = {'model', 'color'} if vendor == 'opencode' else {'model', 'model_reasoning_effort'}
        if not isinstance(values, dict) or values.keys() - keys:
            raise ValueError(f'{vendor}/{name}: unsupported settings')
        if any(not isinstance(v, str) or not v.strip() for v in values.values()):
            raise ValueError(f'{vendor}/{name}: settings must be nonempty strings')
        if 'color' in values and not re.fullmatch(r'#[0-9a-fA-F]{6}', values['color']):
            raise ValueError(f'{vendor}/{name}: invalid color')
    if vendor == 'opencode':
        models = [data.get('default_model')] + [v['model'] for v in overrides.values() if 'model' in v]
        if any(not isinstance(m, str) or not re.fullmatch(r'[^\s/]+/[^\s]+', m) for m in models):
            raise ValueError('OpenCode models require provider/model IDs')
    else:
        limit = data.get('max_concurrent_threads_per_session')
        if type(limit) is not int or limit < 1:
            raise ValueError('Codex concurrency limit must be a positive integer')
        for values in overrides.values():
            if values.get('model_reasoning_effort', 'medium') not in {'minimal', 'low', 'medium', 'high', 'xhigh', 'max', 'ultra'}:
                raise ValueError('Invalid Codex reasoning effort')
    return data


def prompt(role: dict) -> str:
    return COMMON + role['body']


def render(root: Path) -> dict[str, str]:
    entrypoint, roles = load_core(root)
    oc = load_settings(root, 'opencode', set(roles))
    cx = load_settings(root, 'codex', set(roles))
    outputs = {}
    for name, role in sorted(roles.items()):
        cfg = oc['roles'].get(name, {})
        permission = {'edit': 'allow' if role['access'] == 'write' else 'deny'}
        if role['access'] == 'read':
            permission['bash'] = 'deny'
        # Other tools and approvals inherit the host policy. No fictitious tool_use.
        fields = {'description': role['description'],
                  'mode': 'primary' if name == entrypoint else 'subagent',
                  'model': cfg.get('model', oc['default_model'])}
        if 'color' in cfg:
            fields['color'] = cfg['color']
        fm = '\n'.join(f'{k}: {quote(v)}' for k, v in fields.items())
        fm += '\npermission: ' + json.dumps(permission)
        outputs[f'.opencode/agents/{name}.md'] = f'---\n{fm}\n---\n\n<!-- {MARKER}; source: .agents/roles/{name}.md -->\n\n' + prompt(role)
        if name != entrypoint:
            lines = [f'# {MARKER}; do not edit.',
                     f'# Source: .agents/roles/{name}.md',
                     f'name = {quote(name)}', f'description = {quote(role["description"])}',
                     f'sandbox_mode = {quote("workspace-write" if role["access"] == "write" else "read-only")}']
            for key, value in sorted(cx['roles'].get(name, {}).items()):
                lines.append(f'{key} = {quote(value)}')
            lines.append('developer_instructions = ' + quote(prompt(role)))
            text = '\n'.join(lines) + '\n'
            tomllib.loads(text)
            outputs[f'.codex/agents/{name}.toml'] = text
    if entrypoint in cx['roles']:
        raise ValueError('Codex entrypoint is the main session, not a custom subagent override')
    outputs['.codex/config.toml'] = (f'# {MARKER}; settings: .agents/adapters/codex.json\n'
                                    '[agents]\nenabled = true\n'
                                    f'max_concurrent_threads_per_session = {cx["max_concurrent_threads_per_session"]}\n')
    outputs['.opencode/ORGANIZATION.md'] = (f'<!-- {MARKER}; do not edit. -->\n\n'
        '# Agent organization\n\nThe canonical [organization and roster](../.agents/ORGANIZATION.md)\n'
        'and [authoring guide](../.agents/README.md) apply to all adapters.\n'
        'This path is retained for existing references.\n')
    org_path = root / '.agents/ORGANIZATION.md'
    org = org_path.read_text()
    start, end = '<!-- agent-roster:start -->', '<!-- agent-roster:end -->'
    if org.count(start) != 1 or org.count(end) != 1 or org.index(start) > org.index(end):
        raise ValueError('Organization needs one ordered roster marker pair')
    outputs['.agents/ORGANIZATION.md'] = org[:org.index(start)] + roster(organization_fields(entrypoint, roles)) + org[org.index(end)+len(end):]
    return outputs


def sync(root: Path, *, write: bool = False, adopt_existing: bool = False) -> list[str]:
    try:
        outputs = render(root)
        entrypoint, _ = load_core(root)
        if load_json(root / 'opencode.json').get('default_agent') != entrypoint:
            raise ValueError('opencode.json default_agent must match core entrypoint')
        manifest_path = root / MANIFEST
        previous = load_json(manifest_path) if manifest_path.exists() else {'schema_version': 1, 'files': []}
        if previous.get('schema_version') != 1 or not isinstance(previous.get('files'), list):
            raise ValueError('Invalid generated-file manifest')
        if any(not isinstance(p, str) or not p.startswith(('.codex/', '.opencode/', '.agents/')) or '..' in Path(p).parts for p in previous['files']):
            raise ValueError('Unsafe generated-file manifest')
    except (OSError, ValueError, KeyError, TypeError) as exc:
        return [str(exc)]
    errors = []
    expected = set(outputs)
    actual = {p.relative_to(root).as_posix() for directory, pattern in
              [('.opencode/agents', '*.md'), ('.codex/agents', '*.toml')]
              for p in (root / directory).rglob(pattern)}
    extra = (actual | set(previous['files'])) - expected
    if extra:
        errors.append('Unexpected/retired generated paths: ' + ', '.join(sorted(extra)) + '; review/archive explicitly')
    outputs[MANIFEST] = json.dumps({'schema_version': 1, 'files': sorted(expected)}, indent=2) + '\n'
    changes = []
    for relative, content in outputs.items():
        path = root / relative
        # Do not follow generated output symlinks, including a symlinked parent.
        if any(p.is_symlink() for p in [path, *path.parents] if p != root.parent):
            errors.append(f'Refusing symlink output: {relative}')
            continue
        exists = path.exists()
        current = path.read_text() if exists else None
        if current != content:
            if (write and exists and relative not in {'.agents/ORGANIZATION.md', MANIFEST}
                    and MARKER not in current and relative not in previous['files'] and not adopt_existing):
                errors.append(f'Refusing unowned file: {relative}; initial migration requires --adopt-existing')
            changes.append((relative, content))
    if errors:
        return errors
    if not write:
        return [f'Stale or missing: {relative}' for relative, _ in changes]
    # Validate all destinations before any writes. No deletion or silent adoption.
    for relative, content in changes:
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return []


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--write', action='store_true')
    parser.add_argument('--adopt-existing', action='store_true', help='explicit first-migration adoption of existing adapter files')
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    if args.adopt_existing and not args.write:
        parser.error('--adopt-existing requires --write')
    errors = sync(args.root.resolve(), write=args.write, adopt_existing=args.adopt_existing)
    print('\n'.join(errors) if errors else 'Agent core and adapters: OK')
    return bool(errors)


if __name__ == '__main__':
    raise SystemExit(main())
