#!/usr/bin/env python3
"""Generate the language-neutral full wiki catalog in ``index.md``."""

from __future__ import annotations

import argparse
import difflib
from collections import Counter, defaultdict
from pathlib import Path

from wiki_quality_common import LOCALES, WikiPage, load_wiki_pages


GENERATED_MARKER = "<!-- Generated by scripts/generate_wiki_index.py; do not edit by hand. -->"


def _escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _link(page: WikiPage) -> str:
    title = _escape(page.title).replace("[", "(").replace("]", ")")
    return f"[{title}]({page.relative_path.as_posix()})"


def _group_rows(pages: list[WikiPage]) -> list[dict[str, object]]:
    groups: dict[str, list[WikiPage]] = defaultdict(list)
    for page in pages:
        groups[page.translation_group].append(page)
    rows: list[dict[str, object]] = []
    for group_name, members in sorted(groups.items()):
        localized: dict[str, WikiPage] = {}
        for page in members:
            if page.language in LOCALES and page.language not in localized:
                localized[page.language] = page
        statuses = sorted({page.status for page in members})
        roles = sorted({str(page.metadata.get("page_role") or page.metadata.get("type") or "unclassified") for page in members})
        versions = sorted({str(page.metadata.get("semantic_version") or "—") for page in members})
        rows.append(
            {
                "group": group_name,
                "members": members,
                "localized": localized,
                "status": ", ".join(statuses),
                "role": ", ".join(roles),
                "version": ", ".join(versions),
            }
        )
    return rows


def render_index(pages: list[WikiPage]) -> str:
    rows = _group_rows(pages)
    complete = sum(set(row["localized"]) == set(LOCALES) for row in rows)
    missing_files = sum(len(set(LOCALES) - set(row["localized"])) for row in rows)
    status_counts = Counter(page.status for page in pages)
    role_counts = Counter(
        str(page.metadata.get("page_role") or page.metadata.get("type") or "unclassified")
        for page in pages
    )

    lines = [
        GENERATED_MARKER,
        "",
        "# Before We Build — Wiki Catalog",
        "",
        "This is the generated, language-neutral catalog. Reader entrypoints are "
        "the localized `start-here` pages.",
        "",
        "## Inventory",
        "",
        f"- Markdown pages: **{len(pages)}**",
        f"- Translation groups: **{len(rows)}**",
        f"- Complete EN/RU/UK triads: **{complete}**",
        f"- Missing language files: **{missing_files}**",
        "- Document statuses: "
        + ", ".join(f"{name}={count}" for name, count in sorted(status_counts.items())),
        "- Page roles: "
        + ", ".join(f"{name}={count}" for name, count in sorted(role_counts.items())),
        "",
        "## Reader entrypoints",
        "",
    ]

    start_row = next((row for row in rows if row["group"] == "start-here"), None)
    if start_row:
        localized = start_row["localized"]
        for language, label in (("en", "English"), ("ru", "Русский"), ("uk", "Українська")):
            page = localized.get(language)
            lines.append(f"- {label}: {_link(page)}" if page else f"- {label}: _draft not available_")
    else:
        lines.append("- _No start-here translation group found._")

    lines.extend(
        [
            "",
            "## Full catalog",
            "",
            "| Translation group | English | Русский | Українська | Status | Role | Semantic version |",
            "|---|---|---|---|---|---|---|",
        ]
    )
    for row in rows:
        localized = row["localized"]
        cells = [_link(localized[lang]) if lang in localized else "—" for lang in LOCALES]
        lines.append(
            "| "
            + " | ".join(
                [
                    _escape(row["group"]),
                    *cells,
                    _escape(row["status"]),
                    _escape(row["role"]),
                    _escape(row["version"]),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Maintenance",
            "",
            "Regenerate with `python3 scripts/generate_wiki_index.py --write`. "
            "CI verifies this file with `--check`.",
            "",
        ]
    )
    return "\n".join(lines)


def check_index(output: Path, expected: str) -> tuple[bool, str]:
    if not output.exists():
        return False, f"{output} does not exist"
    actual = output.read_text(encoding="utf-8")
    if actual == expected:
        return True, ""
    diff = "".join(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=str(output),
            tofile=f"{output} (generated)",
            n=2,
        )
    )
    return False, diff


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path, help="output path (default: ROOT/index.md)")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = args.root.resolve()
    output = args.output or root / "index.md"
    if not output.is_absolute():
        output = root / output
    rendered = render_index(load_wiki_pages(root))

    if args.write:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")
        print(f"Wrote {output}")
        return 0
    if args.check:
        matches, detail = check_index(output, rendered)
        if matches:
            print(f"OK: {output} is up to date")
            return 0
        print(f"ERROR: {output} is stale; run scripts/generate_wiki_index.py --write")
        if detail:
            print(detail[:12000])
        return 1

    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
